# Generated by Django 5.0 on 2023-12-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
